### ISSUE TITLE
Add qemu builder

### ISSUE THREAD

**Issue by reavon** [NLM-OCCS/occs-packer#10]
In addition to the virtualbox-iso builder, we need to add the [qemu](https://www.packer.io/docs/builders/qemu.html) builder and use the [kvm](https://www.packer.io/docs/builders/qemu.html#accelerator) accelerator. We will need to make sure that both are pushed to AWS for the time being until we can determine the KVM AMI works as expected.

I believe this along with an different kickstart will put us more in line with what the CentOS project is doing with their cloud images.

Once this has been setup and tested, I will open another ticket to look into using the XEN accelerator and then we can test them to determine which has the best performance.

**Comment by danizen** [comment]
This will require more setup. I can work with it now on the PC because packer and virtualbox I have.   To work on this "inside the farm", we'd need a place where this work would take place.  I've done plenty of  qemu and virt-manager stuff in the past, even the virt- whatever shell.   However, I don't want to try to do that on Windows (or in a VirtualBox on Windows).

**Comment by danizen** [comment]
I think my previous comment is incorrect - as long as we leave a virtualbox builder as well, then a Windows user can still proceed to hack on it.

**Comment by reavon** [comment]
This isn't going to work. The Qemu builder doesn't output an ova or ovf which is required by the `amazon-import` post processor.

**Comment by reavon** [comment]
Using the qemu builder will not result in a AMI on AWS... closing.
